// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace QAWorksTest.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ContactUs")]
    public partial class ContactUsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ContactUsPage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ContactUs", "\t As an end user\r\n  I want a contact us page\r\n  So that I can find out more about" +
                    " QAWorks exciting services", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Valid Submission")]
        public virtual void ValidSubmission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Valid Submission", ((string[])(null)));
#line 7
  this.ScenarioSetup(scenarioInfo);
#line 8
    testRunner.Given("I am on the QAWorks Staging Site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("I am on Contactus page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "field",
                        "Value"});
            table1.AddRow(new string[] {
                        "ctl00_MainContent_NameBox",
                        "j.Bloggs"});
            table1.AddRow(new string[] {
                        "ctl00_MainContent_EmailBox",
                        "j.Bloggs@qaworks.com"});
            table1.AddRow(new string[] {
                        "ctl00_MainContent_MessageBox",
                        "please contact me I want to find out more"});
#line 10
    testRunner.Then("I should be able to contact QAWorks with the following information", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate all three fields are  mandatory")]
        public virtual void ValidateAllThreeFieldsAreMandatory()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate all three fields are  mandatory", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("I am on the QAWorks Staging Site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.When("I am on Contactus page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "field",
                        "Value"});
            table2.AddRow(new string[] {
                        "ctl00_MainContent_NameBox",
                        "j.Bloggs"});
            table2.AddRow(new string[] {
                        "ctl00_MainContent_EmailBox",
                        ""});
            table2.AddRow(new string[] {
                        "ctl00_MainContent_MessageBox",
                        "please contact me I want to find out more"});
#line 19
    testRunner.And("I leave email address field empty", ((string)(null)), table2, "And ");
#line 24
 testRunner.Then("I should see error message as \"email address required\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "field",
                        "Value"});
            table3.AddRow(new string[] {
                        "ctl00_MainContent_NameBox",
                        ""});
            table3.AddRow(new string[] {
                        "ctl00_MainContent_EmailBox",
                        "j.Blogs@test.com"});
            table3.AddRow(new string[] {
                        "ctl00_MainContent_MessageBox",
                        "please contact me I want to find out more"});
#line 26
 testRunner.When("I leave name field empty", ((string)(null)), table3, "When ");
#line 31
  testRunner.Then("I should see error message as \"name required\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "field",
                        "Value"});
            table4.AddRow(new string[] {
                        "ctl00_MainContent_NameBox",
                        "J.Bloggs"});
            table4.AddRow(new string[] {
                        "ctl00_MainContent_EmailBox",
                        "j.Blogs@test.com"});
            table4.AddRow(new string[] {
                        "ctl00_MainContent_MessageBox",
                        ""});
#line 33
     testRunner.When("I leave message field empty", ((string)(null)), table4, "When ");
#line 38
  testRunner.Then("I should see error message as \"message required\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("validate email address accepts valid format")]
        [NUnit.Framework.TestCaseAttribute("blogss.com", new string[0])]
        [NUnit.Framework.TestCaseAttribute("blogss@", new string[0])]
        [NUnit.Framework.TestCaseAttribute("@@@", new string[0])]
        [NUnit.Framework.TestCaseAttribute("12323", new string[0])]
        public virtual void ValidateEmailAddressAcceptsValidFormat(string invalidEmail, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("validate email address accepts valid format", exampleTags);
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
testRunner.Given("I amon QAWorks Staging Site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
testRunner.When(string.Format("I enter invalid email \'{0}\'", invalidEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
testRunner.And("I enter name \"jbloggs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
testRunner.And("I enter message \"Please contact me\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
testRunner.And("I submit form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
testRunner.Then("I should see error message as \"Please enter valid email address\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
